/*
  # Add Tavus Conversation URL to Interviews Table
  
  1. New Columns
    - `tavus_conversation_url` - Stores the Daily.co room URL generated by Tavus
    
  2. Purpose
    - Pre-generate conversation URLs during interview setup
    - Allow immediate joining of video calls without waiting for API calls
    - Improve user experience by eliminating waiting time when starting interviews
*/

-- Add tavus_conversation_url column to interviews table
ALTER TABLE interviews
ADD COLUMN IF NOT EXISTS tavus_conversation_url TEXT;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_interviews_tavus_conversation_url 
ON interviews(tavus_conversation_url);